// Generated by CoffeeScript 1.6.3
(function() {
  this.MediaStorage = {
    S3: "s3",
    LOCAL: "local"
  };

  this.url_for = function(media_obj) {
    "Returns the backend url for a media object";
    if (media_obj.storage === MediaStorage.S3) {
      return "" + CLOUDFRONT_URL + media_obj.file_name;
    }
    return "" + BACKEND_URL + UPLOAD_RELATIVE_ENDPOINT + "/" + media_obj.file_name;
  };

  this.page_render = function(obj) {
    $(obj.firstNode).css({
      'opacity': 0
    });
    $(obj.firstNode).css({
      'position': 'relative',
      'left': 100
    });
    return $(obj.firstNode).animate({
      'opacity': 1,
      'left': '0'
    }, 100);
  };

  this.scrollTop = function() {
    return $("html, body").animate({
      scrollTop: 0
    }, "fast");
  };

  this.newAlert = function(title, description, dismissable) {
    var alert;
    if (dismissable == null) {
      dismissable = true;
    }
    alert = $(".alert-sample").clone().removeClass("hidden").removeClass("alert-sample");
    if (!dismissable) {
      $(alert).find(".container-alert-close").remove();
    } else {
      $(alert).find(".loading-gif").remove();
    }
    $(alert).find(".alert-title").text(title);
    $(alert).find(".alert-desc").text(description);
    $(".alert-container").prepend(alert);
    return alert;
  };

}).call(this);
