// Generated by CoffeeScript 1.6.3
(function() {
  this.MediaStorage = {
    S3: "s3",
    LOCAL: "local"
  };

  this.url_for = function(media_obj) {
    "Returns the backend url for a media object";
    if (media_obj.storage === MediaStorage.S3) {
      return "" + CLOUDFRONT_URL + media_obj.file_name;
    }
    return "" + BACKEND_URL + UPLOAD_RELATIVE_ENDPOINT + "/" + media_obj.file_name;
  };

}).call(this);
