#!/bin/sh
rm -r bundle/
meteor bundle unifide.tgz
tar -zxvf unifide.tgz
PORT=3000 MONGO_URL=mongodb://kianwei:thisisnotsecureatall@localhost:27017/unifide-backend ROOT_URL=~/1platform/unifide-platform/ node bundle/main.js