#!/bin/sh
rm -r bundle/
meteor bundle unifide.tgz
tar -zxvf unifide.tgz
cd bundle/server
npm uninstall fibers
npm install fibers
cd ../..
PORT=3000 MONGO_URL=mongodb://localhost:27017/unifide ROOT_URL=. node bundle/main.js
