// Generated by CoffeeScript 1.6.2
(function() {
  var BIZINFO_TEMPLATE;

  BIZINFO_TEMPLATE = {
    OVERVIEW: "bizinfo_overview",
    UPDATE: "bizinfo_update"
  };

  Template.bizinfo.view = function() {
    if ((Session.get("page_template")) === BIZINFO_TEMPLATE.UPDATE) {
      return Template[BIZINFO_TEMPLATE.UPDATE]();
    } else {
      return Template[BIZINFO_TEMPLATE.OVERVIEW]();
    }
  };

}).call(this);
