// Generated by CoffeeScript 1.6.3
(function() {
  var createCashback, getCashbackTemplate;

  this.CASHBACK_SESSION = {
    SUBURL: "CBSubUrl"
  };

  this.CASHBACK_TEMPLATE = {
    MAIN: "cashback_rules",
    COMPOSE_RULE: "cashback_compose",
    TRANSACTION_LOG: "cashback_transaction_log",
    USER_CREDIT_STORE: "cashback_user_values"
  };

  this.CASHBACK_PAGE = {
    MAIN: "rule",
    COMPOSE: "compose",
    TRANSACTION: "log",
    USER_CREDIT: "user-credit"
  };

  Template.cashback.view = function() {
    return Template[getCashbackTemplate()]();
  };

  Template.cashback.rendered = function() {
    return scrollTop();
  };

  Template.cashback_compose.rendered = function() {
    $("#cashback-compose-form").off("submit");
    return $("#cashback-compose-form").on("submit", function(evt) {
      evt.preventDefault();
      return createCashback("true");
    });
  };

  Template.cashback_compose.events = {
    "click .save-active-btn": function(evt) {
      evt.preventDefault();
      return createCashback("true");
    },
    "click .save-btn": function(evt) {
      evt.preventDefault();
      return createCashback();
    }
  };

  createCashback = function(make_active) {
    var dic;
    if (make_active == null) {
      make_active = false;
    }
    if ($("#cashback-compose-form").parsley("validate")) {
      dic = {
        name: $("#name").val,
        description: $("#description").val(),
        perc: $("#perc").val(),
        min_spending: $("#min-spending").val(),
        make_active: make_active
      };
    }
    return Meteor.call("new_cashback", dic, function() {
      Router.navigate("/cashback", true);
      return flashAlert("Cashback created!", "");
    });
  };

  getCashbackTemplate = function() {
    var slugs;
    slugs = Session.get(CASHBACK_SESSION.SUBURL);
    if (slugs == null) {
      return CASHBACK_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === CASHBACK_PAGE.COMPOSE) {
        return CASHBACK_TEMPLATE.COMPOSE_RULE;
      } else if (slugs[0] === CASHBACK_PAGE.TRANSACTION) {
        return CASHBACK_TEMPLATE.TRANSACTION_LOG;
      } else if (slugs[0] === CASHBACK_PAGE.USER_CREDIT) {
        return CASHBACK_TEMPLATE.USER_CREDIT_STORE;
      }
    }
    return CASHBACK_TEMPLATE.MAIN;
  };

}).call(this);
