// Generated by CoffeeScript 1.6.3
(function() {
  var getCashbackTemplate;

  this.CASHBACK_SESSION = {
    SUBURL: "CBSubUrl"
  };

  this.CASHBACK_TEMPLATE = {
    MAIN: "cashback_rules",
    COMPOSE_RULE: "cashback_compose",
    TRANSACTION_LOG: "cashback_transaction_log",
    USER_CREDIT_STORE: "cashback_user_values"
  };

  this.CASHBACK_PAGE = {
    MAIN: "rule",
    COMPOSE: "compose",
    TRANSACTION: "log",
    USER_CREDIT: "user-credit"
  };

  Template.cashback.view = function() {
    return Template[getCashbackTemplate()]();
  };

  Template.cashback.rendered = function() {
    return scrollTop();
  };

  getCashbackTemplate = function() {
    var slugs;
    slugs = Session.get(CASHBACK_SESSION.SUBURL);
    if (slugs == null) {
      return CASHBACK_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === CASHBACK_PAGE.COMPOSE) {
        return CASHBACK_TEMPLATE.COMPOSE_RULE;
      } else if (slugs[0] === CASHBACK_PAGE.TRANSACTION) {
        return CASHBACK_TEMPLATE.TRANSACTION_LOG;
      } else if (slugs[0] === CASHBACK_PAGE.USER_CREDIT) {
        return CASHBACK_TEMPLATE.USER_CREDIT_STORE;
      }
    }
    return CASHBACK_TEMPLATE.MAIN;
  };

}).call(this);
