// Generated by CoffeeScript 1.6.3
(function() {
  this.CASHBACK_SESSION = {
    SUBURL: "CBSubUrl"
  };

  this.CASHBACK_TEMPLATE = {
    MAIN: "cashback_rules",
    COMPOSE_RULE: "cashback_compose",
    TRANSACTION_LOG: "cashback_transaction_log",
    USER_CREDIT_STORE: "cashback_user_values"
  };

  Template.cashback.view = function() {
    return Template[CASHBACK_TEMPLATE.MAIN]();
  };

  Template.cashback.rendered = function() {
    return scrollTop();
  };

}).call(this);
