// Generated by CoffeeScript 1.6.3
(function() {
  var bindCouponComposeForm, createCoupon, getCouponPage;

  this.COUPON_SESSION = {
    SUBURL: "CPSubUrl"
  };

  this.COUPON_TEMPLATE = {
    MAIN: "coupon_all",
    NEW: "coupon_compose"
  };

  this.COUPON_PAGE = {
    MAIN: "all",
    COMPOSE: "new"
  };

  Template.coupon.rendered = function() {
    return scrollTop();
  };

  Template.coupon.view = function() {
    return Template[getCouponPage()]();
  };

  Template.coupon_compose.rendered = function() {
    Meteor.subscribe("all_groups");
    Meteor.subscribe("all_users");
    $("#coupon-compose-form").off("submit");
    bindCouponComposeForm();
    return $("#coupon-compose-form").on("submit", function(evt) {
      evt.preventDefault();
      return createCoupon();
    });
  };

  Template.coupon_compose.groups = function() {
    return Group.find({}, {
      sort: {
        name: 1
      }
    });
  };

  bindCouponComposeForm = function() {
    $("#user-applicable").off("change");
    $("#user-applicable").change(function() {
      $(".select-specific-user").addClass("hidden");
      $(".select-user-grp").addClass("hidden");
      if ($(this).val() === "group") {
        return $(".select-user-grp").removeClass("hidden");
      } else if ($(this).val() === "specific_user") {
        return $(".select-specific-user").removeClass("hidden");
      }
    });
    $("#user").off("focus");
    $("#user").focus(function() {
      var _this = this;
      return searchUserId(function(res, userid, username, email) {
        if (res) {
          $(_this).val("" + username + " " + email);
          return $(_this).attr("data-user-id", userid);
        }
      });
    });
    $("#applicable-on").off("change");
    $("#applicable-on").change(function() {
      $("#select-container").addClass("hidden");
      $("#container-id").removeAttr("data-required");
      $("#select-item").addClass("hidden");
      $("#item-id").removeAttr("data-required");
      if ($(this).val() === "item") {
        $("#select-item").removeClass("hidden");
        return $("#item-id").attr("data-required", "true");
      } else if ($(this).val() === "container") {
        $("#select-container").removeClass("hidden");
        return $("#container-id").attr("data-required", "true");
      }
    });
    $("#lifetime-type").off("change");
    $("#lifetime-type").change(function() {
      $(".date-selectors").addClass("hidden");
      if ($(this).val() === "duration") {
        return $(".date-selectors").removeClass("hidden");
      }
    });
    $(".date-selectors").datetimepicker({
      language: 'en'
    });
    $("#item-id").off("focus");
    $("#item-id").focus(function() {
      var _this = this;
      return searchItemId(function(success, id, name) {
        if (success) {
          $(_this).val(name);
          return $(_this).attr("data-item-id", id);
        }
      });
    });
    $("#container-id").off("focus");
    return $("#container-id").focus(function() {
      var _this = this;
      return searchContainerId(function(success, id, name) {
        if (success) {
          $(_this).val(name);
          return $(_this).attr("data-container-id", id);
        }
      });
    });
  };

  getCouponPage = function() {
    var slugs;
    slugs = Session.get(COUPON_SESSION.SUBURL);
    if (slugs == null) {
      return COUPON_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === COUPON_PAGE.COMPOSE) {
        return COUPON_TEMPLATE.NEW;
      }
    }
    return COUPON_TEMPLATE.MAIN;
  };

  createCoupon = function() {
    var container_id, error, item_id, user_id;
    if ($("#coupon-compose-form").parsley("validate")) {
      error = false;
      item_id = $("#item-id").attr("data-item-id");
      container_id = $("#container-id").attr("data-container-id");
      user_id = $("#user").attr("data-user-id");
      if ($("#applicable-on").val() === "item" && (item_id == null)) {
        error = true;
        flashAlert("Oops", "You need to select an item to continue..");
      }
      if ($("#applicable-on").val() === "container" && (container_id == null)) {
        error = true;
        flashAlert("Oops", "You need to select a container to continue..");
      }
      if ($("#lifetime-type").val() === "duration" && ($("#begins-on").val() === "" || $("#ends-on").val() === "")) {
        error = true;
        flashAlert("Oops", "You need to select a beginning and expiry date to continue..");
      }
      if ($("#user-applicable").val() === "group" && ($("#user-groups").val() == null)) {
        error = true;
        flashAlert("Oops", "You need to select at least a user group to continue..");
      }
      if ($("#user-applicable").val() === "specific_user" && (user_id == null)) {
        error = true;
        flashAlert("Oops", "You need to select a user to continue..");
      }
      if (!error) {
        return Meteor.call("new_coupon", {
          name: $("#name").val(),
          description: $("#description").val(),
          applicable_on: $("#applicable-on").val(),
          item_id: item_id,
          container_id: container_id,
          coupon_type: $("#coupon-type").val(),
          amount: $("#amount").val(),
          min_spending: $("#min-spending").val(),
          lifetime_type: $("#lifetime-type").val(),
          begins_on: $("#begins-on").val(),
          ends_on: $("#ends-on").val(),
          user_applicable: $("#user-applicable").val(),
          user_groups: $("#user-groups").val(),
          user_id: user_id
        }, function() {
          var IS_COUPON_CREATING;
          IS_COUPON_CREATING = false;
          return Router.navigate("/coupon", true);
        });
      }
    }
  };

}).call(this);
