// Generated by CoffeeScript 1.6.3
(function() {
  var IS_DISCOUNT_CREATING, bindFormElements, createDiscount, getDiscountPage;

  this.DISCOUNT_SESSION = {
    SUBURL: "DCSubUrl"
  };

  this.DISCOUNT_TEMPLATE = {
    MAIN: "discount_all",
    NEW: "discount_compose"
  };

  this.DISCOUNT_PAGE = {
    MAIN: "all",
    COMPOSE: "new"
  };

  IS_DISCOUNT_CREATING = false;

  Template.discount.rendered = function() {
    return scrollTop();
  };

  Template.discount.view = function() {
    return Template[getDiscountPage()]();
  };

  Template.discount_compose.rendered = function() {
    bindFormElements();
    return $("#discount-compose-form").submit(function(evt) {
      evt.preventDefault();
      return createDiscount();
    });
  };

  Template.discount_compose.events = {
    "click #save-discount-btn": function() {
      return $("#discount-compose-form").submit();
    }
  };

  getDiscountPage = function() {
    var slugs;
    slugs = Session.get(DISCOUNT_SESSION.SUBURL);
    if (slugs == null) {
      return DISCOUNT_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === DISCOUNT_PAGE.COMPOSE) {
        return DISCOUNT_TEMPLATE.NEW;
      }
    }
    return DISCOUNT_TEMPLATE.MAIN;
  };

  bindFormElements = function() {
    $("#applicable-on").change(function() {
      $("#discount-select-container").addClass("hidden");
      $("#discount-container-id").removeAttr("data-required");
      $("#discount-select-item").addClass("hidden");
      $("#discount-item-id").removeAttr("data-required");
      if ($(this).val() === "item") {
        $("#discount-select-item").removeClass("hidden");
        return $("#discount-item-id").attr("data-required", "true");
      } else if ($(this).val() === "container") {
        $("#discount-select-container").removeClass("hidden");
        return $("#discount-container-id").attr("data-required", "true");
      }
    });
    $("#discount-lifetime-type").change(function() {
      $(".date-selectors").addClass("hidden");
      if ($(this).val() === "duration") {
        return $(".date-selectors").removeClass("hidden");
      }
    });
    $(".date-selectors").datetimepicker({
      language: 'en'
    });
    $("#discount-item-id").focus(function() {
      var _this = this;
      return searchItemId(function(success, id, name) {
        if (success) {
          $(_this).val(name);
          return $(_this).attr("data-item-id", id);
        }
      });
    });
    return $("#discount-container-id").focus(function() {
      var _this = this;
      return searchContainerId(function(success, id, name) {
        if (success) {
          $(_this).val(name);
          return $(_this).attr("data-container-id", id);
        }
      });
    });
  };

  createDiscount = function() {
    if ($("#discount-compose-form").parsley("validate")) {
      if (!IS_DISCOUNT_CREATING) {
        IS_DISCOUNT_CREATING = true;
        return Meteor.call("new_discount", {
          name: $.trim($("#discount-name").val()),
          description: $.trim($("#description").val()),
          applicable_on: $("#applicable-on").val(),
          item_id: $("#discount-item-id").attr("data-item-id"),
          container_id: $("#discount-item-id").attr("data-container-id"),
          discount_type: $("#discount-type").val(),
          amount: $("#amount").val(),
          min_order: $("#min-spending").val(),
          duration: $("#discount-lifetime-type").val(),
          begins_on: $("#begins-on").val(),
          ends_on: $("#begins-on").val()
        }, function() {
          IS_DISCOUNT_CREATING = false;
          flashAlert("Discount is created!", "");
          return Router.navigate("/discount", true);
        });
      }
    }
  };

}).call(this);
