// Generated by CoffeeScript 1.6.3
(function() {
  var createUser_callback, loginUser_callback;

  Template.page_login.rendered = function() {
    var box, p, page;
    $('body').css('background', 'url("/media/img/login-bg.png")');
    page = Session.get("page");
    p = page.split('/');
    if (p[1] === "admin-register") {
      box = $('.slide-login');
      $(box).html(Template['page_login_register']());
    }
    return $("#login-form").submit(function(evt) {
      evt.preventDefault();
      return Meteor.loginWithPassword($("#loginUser").val(), $("#loginPass").val(), loginUser_callback);
    });
  };

  Template.page_login.events = {
    'click #login': function() {
      return Meteor.loginWithPassword($("#loginUser").val(), $("#loginPass").val(), loginUser_callback);
    },
    'click #signup': function() {
      return Accounts.createUser({
        username: $('#signupUser').val(),
        email: $('#signupEmail').val(),
        password: $('#signupPass').val()
      }, createUser_callback);
    },
    'click #register-nav': function(event) {
      var box;
      event.preventDefault();
      box = $('.slide-login');
      return box.animate({
        opacity: 0
      }, 500, function() {
        var box2;
        box2 = Template['page_login_register']();
        $(box).html(box2);
        return box.animate({
          'left': '+=400'
        }, 50, function() {
          $('.slide-login').css({
            'opacity': 1
          });
          return $('.slide-login').animate({
            'left': '-=400'
          }, 500);
        });
      });
    },
    'click #login-nav': function(event) {
      var box;
      event.preventDefault();
      box = $('.slide-login');
      return box.animate({
        opacity: 0
      }, 500, function() {
        var box2, box3;
        box2 = Template['page_login']();
        box3 = $(box2).children()[0];
        $(box).html($(box3).children());
        return box.animate({
          'left': '-=400'
        }, 50, function() {
          $('.slide-login').css({
            'opacity': 1
          });
          return $('.slide-login').animate({
            'left': '+=400'
          }, 500);
        });
      });
    },
    'focus .login-input': function(event) {
      $(event.target).parent().parent().css({
        'border-left': '4px solid #2d89ef',
        'background-color': '#f5f5f5'
      });
      return $(event.target).parent().parent().css({
        'padding-left': '36px'
      });
    },
    'blur .login-input': function(event) {
      $(event.target).parent().parent().css({
        'border-left': '',
        'background-color': ''
      });
      return $(event.target).parent().parent().css({
        'padding-left': '40px'
      });
    },
    'mouseenter .login-box-register': function(event) {
      return $(event.target).css({
        '-moz-opacity': '0.6',
        '-webkit-opacity': '0.6',
        'opacity': '0.6'
      });
    },
    'mouseleave .login-box-register': function(event) {
      return $(event.target).css({
        '-moz-opacity': '0.25',
        '-webkit-opacity': '0.25',
        'opacity': '0.25'
      });
    },
    'click #forgotpassword-nav': function(event) {
      var email;
      email = prompt("Username to reset ?", "");
      return Meteor.call('get_user_email', email, function(error, result) {
        if (!result) {
          return console.log(error);
        } else {
          console.log(result);
          return Accounts.forgotPassword({
            email: result
          });
        }
      });
    }
  };

  createUser_callback = function(error) {
    if (error == null) {
      return Router.navigate("", true);
    } else {
      return bootbox.alert(error);
    }
  };

  loginUser_callback = function(error) {
    if (error == null) {
      return Router.navigate("", true);
    } else {
      return bootbox.alert("Error logging in. " + error);
    }
  };

}).call(this);
