// Generated by CoffeeScript 1.6.2
(function() {
  var ORDERS_TEMPLATE;

  ORDERS_TEMPLATE = {
    TABLE: "orders_table"
  };

  Template.orders.view = function() {
    return Template[ORDERS_TEMPLATE.TABLE]();
  };

}).call(this);
