// Generated by CoffeeScript 1.6.3
(function() {
  var ITEMS_PER_PAGE, createOrder, getPage, getPageNo, rehashOrderItems;

  this.ORDER_SESSION = {
    SUBURL: "ORDERSubUrl",
    ID_FILTER: "ORDERIdFilter",
    USER_ID_FILTER: "ORDERUserIdFilter"
  };

  this.ORDER_TEMPLATE = {
    MAIN: "order_all",
    NEW: "order_compose"
  };

  this.ORDER_PAGE = {
    MAIN: "all",
    COMPOSE: "new"
  };

  ITEMS_PER_PAGE = 20;

  Template.order.rendered = function() {
    return scrollTop();
  };

  Template.order.view = function() {
    return Template[getPage()]();
  };

  Template.order_all.created = function() {
    Meteor.subscribe("all_users");
    Meteor.subscribe("all_items");
    Meteor.subscribe("all_orders");
    Session.set(ORDER_SESSION.USER_ID_FILTER, null);
    return Session.set(ORDER_SESSION.ID_FILTER, null);
  };

  Template.order_all.rendered = function() {
    $("#filter-by-id").off("change paste keyup");
    return $("#filter-by-id").on("change paste keyup", function(evt) {
      return Session.set(ORDER_SESSION.ID_FILTER, $(evt.target).val());
    });
  };

  Template.order_all.events = {
    "click #search-by-user": function(evt) {
      return searchUserId(function(success, user_id, username, email) {
        $("#filter-by-id").val("");
        Session.set(ORDER_SESSION.ID_FILTER, null);
        return Session.set(ORDER_SESSION.USER_ID_FILTER, user_id);
      });
    },
    "click [data-expand]": function(evt) {
      var elem, id;
      elem = $(evt.target).parents("[data-expand]")[0];
      id = $(elem).attr("data-expand");
      $("[data-expanded]").addClass("hidden");
      return $("[data-expanded=" + id + "]").removeClass("hidden");
    }
  };

  Template.order_all.orders = function() {
    var dic, id_filter, page_no_0_idx, user_id_filter;
    page_no_0_idx = getPageNo() - 1;
    id_filter = Session.get(ORDER_SESSION.ID_FILTER);
    user_id_filter = Session.get(ORDER_SESSION.USER_ID_FILTER);
    dic = {};
    if ((id_filter != null) && id_filter.length > 0) {
      dic = {
        _id: new Meteor.Collection.ObjectID(id_filter)
      };
    } else if ((user_id_filter != null) && user_id_filter.length > 0) {
      dic = {
        user_id: user_id_filter
      };
    }
    return Order.find(dic, {
      limit: ITEMS_PER_PAGE,
      skip: page_no_0_idx * ITEMS_PER_PAGE,
      sort: {
        modification_timestamp_utc: -1
      },
      transform: function(doc) {
        var all_items, items_descriptive, last_mod;
        last_mod = moment(doc.timestamp_utc);
        doc["id"] = doc._id.valueOf();
        doc["timestamp"] = last_mod.format('MMMM Do YYYY');
        all_items = [];
        items_descriptive = [];
        _.each(doc.items, function(item_desc_obj) {
          var item, qty;
          item = ITMItems.findOne({
            _id: item_desc_obj.obj_id
          });
          qty = item_desc_obj.quantity;
          all_items.push(item.name);
          return items_descriptive.push("" + item.name + " &times; " + qty);
        });
        doc["all_items"] = all_items.join(", ");
        doc["item_descriptive"] = items_descriptive.join("</br>");
        return doc;
      }
    });
  };

  Template.order_all.current_page = function() {
    return getPageNo();
  };

  Template.order_all.next_page_url = function() {
    var next_page, page_no;
    page_no = getPageNo();
    next_page = page_no + 1;
    return "/order/" + next_page;
  };

  Template.order_all.prev_page_url = function() {
    var page_no, prev_page;
    page_no = getPageNo();
    prev_page = page_no - 1;
    return "/order/" + prev_page;
  };

  Template.order_all.has_next = function() {
    var total_items, total_pages;
    total_items = Order.find({}).count();
    total_pages = Math.ceil(total_items / ITEMS_PER_PAGE);
    return getPageNo() < total_pages;
  };

  Template.order_all.has_prev = function() {
    return getPageNo() >= 2;
  };

  Template.order_compose.created = function() {
    Meteor.subscribe("all_users");
    Meteor.subscribe("all_shipping");
    return Meteor.subscribe("all_items");
  };

  Template.order_compose.rendered = function() {
    $("#order-compose-form").off("submit");
    return $("#order-compose-form").on("submit", function(evt) {
      evt.preventDefault();
      return createOrder();
    });
  };

  Template.order_compose.shipping_methods = function() {
    return ShippingRule.find({}, {
      transform: function(doc) {
        doc["id"] = doc._id.valueOf();
        return doc;
      }
    });
  };

  Template.order_compose.events = {
    "click .submit-btn": function(evt) {
      evt.preventDefault();
      return createOrder();
    },
    "click #add-order-item-btn": function(evt) {
      var order_item_template;
      order_item_template = $("#order-item-template").clone().removeAttr("id").removeClass("hidden");
      $("#order-item-container").append(order_item_template);
      return rehashOrderItems();
    },
    "click .rm-order-item-btn": function(evt) {
      $(evt.target).parents(".control-group").remove();
      return rehashOrderItems();
    },
    "focus #user_id": function(evt) {
      return searchUserId(function(success, user_id, username, email) {
        if (success) {
          return $(evt.target).val("" + username + " " + email).attr("data-user-id", user_id);
        }
      });
    },
    "click .item-selection": function(evt) {
      return searchItemId(function(success, item_id, item_name) {
        if (success) {
          return $(evt.target).val(item_name).attr("data-item-id", item_id);
        }
      });
    }
  };

  getPageNo = function() {
    var slugs;
    slugs = Session.get(ORDER_SESSION.SUBURL);
    if (slugs == null) {
      return 1;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      return parseInt(slugs[0]);
    }
    return 1;
  };

  rehashOrderItems = function() {
    var i;
    i = 1;
    return _.each($(".order-item"), function(order_item) {
      if ($(order_item).attr("id") == null) {
        $(order_item).find(".item_no").text(i);
        return i += 1;
      }
    });
  };

  createOrder = function() {
    var dic;
    if ($("#order-compose-form").parsley("validate")) {
      dic = {
        apply_debits_credits: $("apply_debits_credits").val(),
        user_id: $("#user_id").attr("data-user-id"),
        status: $("#status").val(),
        user_notes: $("#request-notes").val(),
        admin_notes: $("#admin-notes").val(),
        apply_coupon: $("#coupon-code").val(),
        shipping_method: $("#shipping-method").val(),
        items: []
      };
      _.each($(".order-item"), function(order_item) {
        var item_id, quantity;
        if ($(order_item).attr("id") == null) {
          quantity = $(".qty").val();
          item_id = $(".item-selection").attr("data-item-id");
          return dic.items.push({
            obj_id: item_id,
            quantity: quantity
          });
        }
      });
      dic.items = JSON.stringify(dic.items);
      return Meteor.call("new_manual_order", dic, function() {
        return Router.navigate("/order", {
          trigger: true
        });
      });
    }
  };

  getPage = function() {
    var slugs;
    slugs = Session.get(ORDER_SESSION.SUBURL);
    if (slugs == null) {
      return ORDER_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === ORDER_PAGE.COMPOSE) {
        return ORDER_TEMPLATE.NEW;
      }
    }
    return ORDER_TEMPLATE.MAIN;
  };

}).call(this);
