// Generated by CoffeeScript 1.6.3
(function() {
  var ITEMS_PER_PAGE, createShipping, getPage;

  this.SHIPPING_SESSION = {
    SUBURL: "SHIPPINGSubUrl"
  };

  this.SHIPPING_TEMPLATE = {
    MAIN: "shipping_all",
    NEW: "shipping_compose"
  };

  this.SHIPPING_PAGE = {
    MAIN: "all",
    COMPOSE: "new"
  };

  ITEMS_PER_PAGE = 20;

  Template.shipping.rendered = function() {
    return scrollTop();
  };

  Template.shipping.view = function() {
    return Template[getPage()]();
  };

  Template.shipping_compose.rendered = function() {
    $("#shipping-compose-form").off("submit");
    return $("#shipping-compose-form").on("submit", function(evt) {
      evt.preventDefault();
      return createShipping();
    });
  };

  Template.shipping_compose.events = {
    "click .submit-btn": function(evt) {
      evt.preventDefault();
      return createShipping();
    }
  };

  createShipping = function() {
    var data_lis, dic, entry, _i, _len;
    if ($("#shipping-compose-form").parsley("validate")) {
      data_lis = $("#shipping-compose-form").serializeArray();
      dic = {};
      for (_i = 0, _len = data_lis.length; _i < _len; _i++) {
        entry = data_lis[_i];
        dic[entry.name] = entry.value;
      }
      return Meteor.call("new_shipping_method", dic, function() {
        return Router.navigate("/shipping", true);
      });
    }
  };

  getPage = function() {
    var slugs;
    slugs = Session.get(SHIPPING_SESSION.SUBURL);
    if (slugs == null) {
      return SHIPPING_TEMPLATE.MAIN;
    }
    slugs = slugs.split("/");
    slugs = _.filter(slugs, function(s) {
      return s !== "";
    });
    if (slugs.length >= 1) {
      if (slugs[0] === SHIPPING_PAGE.COMPOSE) {
        return SHIPPING_TEMPLATE.NEW;
      }
    }
    return SHIPPING_TEMPLATE.MAIN;
  };

}).call(this);
