// Generated by CoffeeScript 1.6.3
(function() {
  Accounts.onCreateUser(function(options, user) {
    var result;
    result = Meteor.http.put(BACKEND_URL + "account/user/", {
      params: {
        user_id: user._id
      }
    });
    if (result.statusCode !== 200) {
      console.log(result.error);
    }
    return user;
  });

}).call(this);
